# Shopify App Configuration
# https://shopify.dev/docs/apps/tools/cli/configuration

name = "flowmend"
client_id = "655eabe3197f81c524f280f0b57b7cf8"
application_url = "https://flowmend-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://flowmend-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
    topics = [ "app/uninstalled" ]
    uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
    compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
    uri = "/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "flowmend.myshopify.com"
